syllable_map = {
    "Maayong_Buntag" : ["Ma", "a", "yong ", " Bun", "tag"],
    "Maayong_Udto" : ["Ma", "a", "yong ", "Ud", "to"],
    "Maayong_Hapon" : ["Ma", "a", "yong ", "Ha", "pon"],
    "Maayong_Gabii" : ["Ma", "a", "yong ", "Ga", "bi", "i"],
    "Maayong_Adlaw" : ["Ma", "a", "yong ", "Ad", "law"],
    "Kumusta_Ka" : ["Ku", "mus", "ta ", "Ka"],
    "Didto" : ["Did", "to"],
    "Dani" : ["Da", "ni"],
    "Wala" : ["Wa", "la"],
    "Wala_None" : ["Wa", "la"],
    "Too" : ["To", "o"],
    "Asa_Ang" : ["A", "sa", "Ang"],
    "Taas" : ["Ta", "as"],
    "Ubos" : ["U", "bos"],
    "Atubangan" : ["A", "tu", "ba", "ngan"],
    "Likod" : ["Li", "kod"],
    "Ikaw" : ["I", "kaw"],
    "Ako" : ["A", "ko"],
    "Siya" : ["Si", "ya"],
    "Sila" : ["Si", "la"],
    "Imoha" : ["I", "mo", "ha"],
    "Imohang" : ["I", "mo", "hang"],
    "Akoa" : ["A", "ko", "a"],
    "Akoang" : ["A", "ko", "ang"],
    "Anak" : ["A", "nak"], 
    "Bata" : ["Ba", "ta"],
    "Inahan" : ["I", "na", "han"],
    "Amahan" : ["A", "ma", "han"],
    "Bana" : ["Ba", "na"],
    "Asawa" : ["A", "sa", "wa"],
    "Wala" : ["Wa", "la"],
    "Isa" : ["I", "sa"],
    "Duha" : ["Du", "ha"],
    "Tulo" : ["Tu", "lo"],
    "Upat" : ["U", "pat"],
    "Lima" : ["Li", "ma"],
    "Unom" : ["U", "nom"],
    "Pito" : ["Pi", "to"],
    "Walo" : ["Wa", "lo"],
    "Siyam" : ["Si", "yam"],
    "Napulo" : ["Na", "pu", "lo"],
    "Tanan" : ["Ta", "nan"],
    "Kabalo_Ka_Mag_Tagalog" : ["Ka", "ba", "lo ", "Ka ", "Mag ", "Ta", "ga", "log?"],
    "Kabalo_Ka_Mag_English" : ["Ka", "ba", "lo ", "Ka ", "Mag ", "Eng", "lish?"],
    "Palihog" : ["Pa", "li", "hog"],
    "Mangayo_Ko_Ug_Menu" : ["Ma", "nga", "yo ", "Ko ", "Ug ", "Me", "nu"],
    "Palihog_Ko_Ug_Menu" : ["Pa", "li", "hog ", "Ko ", "Ug ", "Me", "nu"],
    "Akoang_Anak" : ["A", "ko", "ang ", "A", "nak"],
    "Akoang_Amahan" : ["A", "ko", "ang ", "A", "ma", "han"],
    "Akoa_Nang_Anak" : ["A", "ko", "a ", "Nang ", "A", "nak"],
    "Akoa_Nang_Inahan" : ["A", "ko", "a ", "Nang ", "I", "na", "han"],
    "Iyaha_Ning_Bana" : ["I", "ya", "ha ", "Ning ", "Ba", "Na"],
    "Siya_Ang_Akoang_Asawa" : ["Si", "ya ", "Ang ", "A", "ko", "ang ", "A", "sa", "wa"],
    "Sila_Akoang_Mga_Anak" : ["Si", "la ", "A", "ko", "ang ", "Mga ", "A", "nak"]
}
